# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d036e4b7a1e2dc1e03231b6a9925748ca7a7b6c82c6766aece658c23151fe42d43f265571681e07483822fef0d379aad3bf7873e38a8a1a4d489c22ecedd8f2

test:
  secret_key_base: 0078c8bdcfb494861a395e4a1a101d8260bd978461552a8c2337dba4c7387fa4d23a2c50c9339e535e3f8dce1378d6193f8b2b2e7615fbf7f020da8e81f4c90e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
